// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW3GIWToCtECxO_wNFGIN7L00KUHQYYW0',
    appId: '1:145622563711:web:0a348ced6defea05eeb84a',
    messagingSenderId: '145622563711',
    projectId: 'flutterproject-f6071',
    authDomain: 'flutterproject-f6071.firebaseapp.com',
    storageBucket: 'flutterproject-f6071.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqIN_iigJ9Hhl2xf-IkM3DUib6LZ14lRU',
    appId: '1:145622563711:android:7d6b631015233696eeb84a',
    messagingSenderId: '145622563711',
    projectId: 'flutterproject-f6071',
    storageBucket: 'flutterproject-f6071.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU69TBUY2IiOAt9KXRTk6b9H9h072GKxY',
    appId: '1:145622563711:ios:50b98735ec3da36beeb84a',
    messagingSenderId: '145622563711',
    projectId: 'flutterproject-f6071',
    storageBucket: 'flutterproject-f6071.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );
}
